[package]
name = "redis_raw"
version = "0.1.0"
authors = ["amin roosta <amin.roosta@outlook.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = [
    "tcp", "macros", "rt-core", "dns", "io-util"
] }
thiserror = "1.0"